import Navbar from "@/Components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Container from "@/Components/Container";

import { CartProvider } from "@/Context/UserContext";
import Footer from "@/Components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Krrunch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Container>
            <Navbar className="fixed" />
            {children}
            <Footer />
          </Container>
        </CartProvider>
      </body>
    </html>
  );
}
